//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineProject.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MachineProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   직접입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ComboBox_DomainUserBy {
            get {
                return ResourceManager.GetString("ComboBox_DomainUserBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 가입된 이메일입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_EmpEmailAlreadyExist_msg {
            get {
                return ResourceManager.GetString("Error_EmpEmailAlreadyExist_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   존재하지 않는 이메일 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_EmpEmailNotExist_msg {
            get {
                return ResourceManager.GetString("Error_EmpEmailNotExist_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 존재하는 직원코드입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_EmpIDAlreadyExist_msg {
            get {
                return ResourceManager.GetString("Error_EmpIDAlreadyExist_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   존재하지 않는 사용자입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_EmpIDNotExist_msg {
            get {
                return ResourceManager.GetString("Error_EmpIDNotExist_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 틀렸습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_EmpWrongPwd_msg {
            get {
                return ResourceManager.GetString("Error_EmpWrongPwd_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   고장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MachineState_Crash {
            get {
                return ResourceManager.GetString("MachineState_Crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MachineState_Run {
            get {
                return ResourceManager.GetString("MachineState_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MachineState_Running {
            get {
                return ResourceManager.GetString("MachineState_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MachineState_Stop {
            get {
                return ResourceManager.GetString("MachineState_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중지중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MachineState_Stopping {
            get {
                return ResourceManager.GetString("MachineState_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ^[a-zA-Z0-9_-]{5,20}$과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Regex_idEx {
            get {
                return ResourceManager.GetString("Regex_idEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID는 5~20자의 영문 소문자, 숫자와 특수기호(_),(-)만 사용 가능합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Regex_idEx_msg {
            get {
                return ResourceManager.GetString("Regex_idEx_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ^[가-힣]{2,4}|[a-zA-Z]{2,10}\s[a-zA-Z]{2,10}$과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Regex_nameEx {
            get {
                return ResourceManager.GetString("Regex_nameEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름을 확인해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Regex_nameEx_msg {
            get {
                return ResourceManager.GetString("Regex_nameEx_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ^[0-9]{2,3}-[0-9]{3,4}-[0-9]{4}$과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Regex_phoneEx {
            get {
                return ResourceManager.GetString("Regex_phoneEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   휴대폰 번호를 확인해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Regex_phoneEx_msg {
            get {
                return ResourceManager.GetString("Regex_phoneEx_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ^(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&amp;*-]).{8,}$과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Regex_pwdEx {
            get {
                return ResourceManager.GetString("Regex_pwdEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호는 숫자1이상, 영문자1이상, 특수문자 1이상, 글자수 8자리 이상입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Regex_pwdEx_msg {
            get {
                return ResourceManager.GetString("Regex_pwdEx_msg", resourceCulture);
            }
        }
    }
}
