// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~M:IceCreamManager.BOM_AmountSearch.btnApply_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.BOMupdateVO.bom_ChildEach")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.BOMupdateVO.mat_Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.BOMupdateVO.mat_No")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.BOMupdateVO.mat_ParentNo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.BOMVO.bom_ChildEach")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.BOMVO.mat_ChildNo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.BOMVO.mat_ParentNo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsTypVO.mtt_Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsTypVO.mtt_No")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.bom_ChildEach")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mat_ChildNo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mat_Cost")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mat_Each")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mat_MinSize")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mat_Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mat_No")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mat_ParentNo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mat_Unit")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mtt_Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.mtt_No")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsVO.off_No")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.Global.cus_Id")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.Global.cus_Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.Global.cus_Password")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~M:IceCreamManager.BOM_Amount.btnEcxel_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.bom_ChildEach")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mat_ChildNo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mat_Cost")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mat_Each")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mat_MinSize")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mat_Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mat_No")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mat_ParentNo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mat_Unit")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mtt_Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.mtt_No")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("스타일", "IDE1006:명명 스타일", Justification = "<보류 중>", Scope = "member", Target = "~P:IceCreamManager.VO.MaterialsBOMConnectVO.off_No")]