SELECT * FROM T_SAMPLE_DATA001
PIVOT (SUM(OUT_QTY) FOR OUT_DT
	IN ([20191231],[20200101],[20200102],[20200103],[20200104],[20200105],[20200106],[20200107])
	)
	AS P;


SELECT * FROM (SELECT ITEM, OUT_DT, OUT_QTY FROM T_SAMPLE_DATA001) AS T
PIVOT (SUM(OUT_QTY) FOR OUT_DT
	IN ([20191231],[20200101],[20200102],[20200103],[20200104],[20200105],[20200106],[20200107])
	)
	AS P


SELECT * FROM 
(SELECT ALL_ITEM.OUT_DT, ALL_ITEM.ITEM, ISNULL(C.OUT_QTY, 0) OUT_QTY
	FROM ( SELECT A.OUT_DT, B.ITEM 
			FROM 
				(SELECT DISTINCT OUT_DT FROM T_SAMPLE_DATA001) A
			  , (SELECT DISTINCT ITEM FROM T_SAMPLE_DATA001) B
		 ) ALL_ITEM
	LEFT OUTER JOIN T_SAMPLE_DATA001 C ON ALL_ITEM.OUT_DT = C.OUT_DT AND ALL_ITEM.ITEM = C.ITEM
	) T 
PIVOT (SUM(OUT_QTY) FOR OUT_DT
IN ([20191231],[20200101],[20200102],[20200103],[20200104],[20200105],[20200106],[20200107])
)
AS P


--커서 이용 문자열 연결
DECLARE @QRY           VARCHAR(MAX)  --동적쿼리(피벗컬럼)
           , @FIRST_DATA  VARCHAR(30)    --첫번째 데이터
           , @ETC_DATA    VARCHAR(30)    --그 외 데이터
           , @PIVOT_COL   VARCHAR(MAX) --피벗컬럼목록(IN)
           , @CNT            INTEGER           --데이터 건수
           , @PIVOT_QRY   VARCHAR(MAX) --피벗쿼리

DECLARE C1 CURSOR FOR
SELECT '[' + Z.OUT_DT2 + ']' FIRST_DATA
        , ',[' + Z.OUT_DT2 + ']' ETC_DATA
  FROM (
			 SELECT CONVERT(VARCHAR,A.OUT_DT,112) OUT_DT2
			  FROM T_SAMPLE_DATA001 A
			 GROUP BY A.OUT_DT
		   ) Z
  ORDER BY Z.OUT_DT2

SET @CNT = 0
SET @PIVOT_COL = ''

OPEN C1
FETCH C1 INTO @FIRST_DATA, @ETC_DATA
WHILE(@@FETCH_STATUS <> -1)
BEGIN
   SET @CNT = @CNT + 1

   --최초일 경우 쉼표 없고, 그 외에는 맨 앞 쉼표 포함처리
   IF @CNT = 1 BEGIN
      SET @PIVOT_COL = @PIVOT_COL + @FIRST_DATA
   END
   ELSE BEGIN
      SET @PIVOT_COL = @PIVOT_COL + @ETC_DATA
   END

   PRINT '@PIVOT_COL ********* ' + @PIVOT_COL;

   FETCH C1 INTO @FIRST_DATA, @ETC_DATA
END
CLOSE C1
DEALLOCATE C1


SET @QRY = ''
SET @QRY = @QRY + '
SELECT *
  FROM (
    SELECT ALL_OUT_DT_ITEM.OUT_DT, ALL_OUT_DT_ITEM.ITEM, ISNULL(C.OUT_QTY,0) OUT_QTY
      FROM (
                 SELECT A.OUT_DT, B.ITEM
                  FROM (SELECT DISTINCT OUT_DT FROM T_SAMPLE_DATA001) A
                         , (SELECT DISTINCT ITEM FROM T_SAMPLE_DATA001) B
               ) ALL_OUT_DT_ITEM
        LEFT OUTER JOIN T_SAMPLE_DATA001 C ON ALL_OUT_DT_ITEM.OUT_DT = C.OUT_DT AND ALL_OUT_DT_ITEM.ITEM = C.ITEM
     ) T
	 PIVOT (SUM(OUT_QTY)
     FOR OUT_DT IN (' + @PIVOT_COL + ')) AS P'

PRINT '@QRY 쿼리 ********* ' + @QRY;

EXEC (@QRY)

